### ISSUE TITLE
hardware address calculation bug

### ISSUE THREAD

**Issue by victorstewart** [beyonddream/snowid#1]
there's technically a bug on this line https://github.com/beyonddream/snowid/blob/0a6c4abc99bc80c84979e24ad1f085a905912bc3/snowid_util.c#L91

you need to `+ 1` to strlen so that the terminal null characters are also compared, otherwise the user could specify `eno1` but the function would hit on `eno10`. obviously i doubt this would ever be reached, but in the interest of absolute correctness!

**Comment by victorstewart** [comment]
the loopback check could also be moved outside of the loop, and the strncmp(ifa->ifa_name, interface, strlen(interface)) moved to the very beginning of the loop (no sense checking or calculating anything else if this is false)

**Comment by beyonddream** [comment]
> the loopback check could also be moved outside of the loop, and the `strncmp(ifa->ifa_name, interface, strlen(interface))` moved to the very beginning of the loop (no sense checking or calculating anything else if this is false)

1) Not sure how loopback check can be moved outside the loop. I don't want to assume it is going to be first in the list either.
2) Regarding moving the comparison check to the beginning, the behavior of this function is that if the check is false always, it should pick a random one (right now it picks the last one) from the array of hw addresses.
